const nomenclador = [
'Acompañamiento Terapéutico por hora',
'Acompañante terapéutico en ámbito escolar',
'Centro de Dia Jornada Doble Categoría A',
'Centro de Dia Jornada Doble Categoría B',
'Centro de Dia Jornada Doble Categoría C',
'Centro de Dia Jornada Simple Categoría A',
'Centro de Dia Jornada Simple Categoría B',
'Centro de Dia Jornada Simple Categoría C',
'Centro Educativo Terapéutico Jornada Doble Cat A',
'Centro Educativo Terapéutico Jornada Simple Cat A',
'Centro Educativo Terapéutico Jornada Simple Cat B',
'CET Jornada Doble Categoría B',
'CET Jornada Doble Categoría C',
'CET Jornada Simple Categoría C',
'Consulta para Discapacidad',
'Cuidadora en Internación domiciliaria por hora',
'Enfermeria en Internación domiciliaria por hora',
'Escolaridad Formación Laboral Jorn Doble Cat B',
'Escolaridad Formación Laboral Jorn Doble Cat C',
'Escolaridad Formación Laboral Jornada Doble Cat A',
'Escolaridad Formación Laboral Jornada Simple Categ A',
'Escolaridad Formación Laboral Jornada Simple Categ B',
'Escolaridad Formación Laboral Jornada Simple Categ C',
'Escolaridad Pre- Primaria y Primaria Jornada Doble',
'Escolaridad Pre- Primaria y Primaria Jornada Simpl',
'ESCOLARIDAD PRIMARIA  JORNADA DOBLE  CATEGORÍA   A',
'ESCOLARIDAD PRIMARIA  JORNADA SIMPLE CATEGORÍA   A',
'ESCOLARIDAD PRIMARIA  JORNADA SIMPLE CATEGORÍA B',
'ESCOLARIDAD PRIMARIA JORNADA COMPLETA CATEGORÍA B',
'Estimulación Temprana (mensual)',
'Estimulación Temprana para DISCAPACIDAD',
'Estimulación Visual Discapacidad',
'Fonoaudiología para DISCAPACIDAD',
'Hidroterapia',
'Hogar Lunes a Viernes con Centro de Dia Cat. A',
'Hogar Lunes a Viernes con Centro de Dia Cat. B',
'Hogar Lunes a Viernes con Centro de Dia Cat.C',
'Hogar Permanente Categoría A',
'Hogar Permanente Categoría B',
'Hogar Permanente Categoría C',
'Hogar Permanente Con Centro de Dia Categoría A',
'Hogar Permanente Con Centro de Dia Categoría B',
'Hogar Permanente Con Centrol de Dia Categoría C',
'Hogar Permanente con CET Categoría A',
'Hogar Permanente con CET Categoría B',
'Hogar Permanente con CET Categoría C',
'Hogar Permanente con Formación Laboral Categoría A',
'Hogar Permanente con Formación Laboral Categoría B',
'Hogar Permanente con Formación Laboral Categoría C',
'Kinesiología para DISCAPACIDAD',
'Material Descartable',
'Módulo  Maestro de Apoyo por hora',
'Módulo de Apoyo a la Integración escolar ',
'Modulo Maestro de Apoyo(Mensual)',
'Musicoterapia para Discapacidad',
'Prestaciones de Apoyo',
'Psicomotricidad para DISCAPACIDAD',
'Psicopedagogía para DISCAPACIDAD',
'Psicoterapia para DISCAPACIDAD',
'Rehabilitación - Internación (mensual)',
'Rehabilitación - Modulo Integral Simple (semanal)',
'Rehabilitación-Hosp de Día Jornada Doble (mensual)',
'Rehabilitación-Hosp de Día Jornada Simple (mensual)',
'Rehabilitación-Modulo Integral Intensivo (semanal)',
'Residencia Permanente Categoría A',
'Residencia Permanente Categoría B',
'Residencia Permanente Categoría C',
'Sesión Orientación a Padres',
'Terapia Ocupacional DISCAPACIDAD',
'Transporte * Km',

]